import { BuilderTemplate } from '../templates';

const INK = '#2d2926';
const ACCENT = '#b85c38';
const OFF = '#f7f5f1';
const MID = '#7a7368';

export const ascent: BuilderTemplate = {
  id: 'ascent',
  name: 'Ascent',
  description: 'Editorial-style landing page for an early-stage startup — pitch the product, recruit a co-founder, and show the roadmap.',
  category: 'SaaS',
  type: 'both',
  step_type: 'sales_page',
  is_premium: true,
  thumbnail: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=1200&auto=format&fit=crop',
  content: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'min-h-screen bg-white text-slate-900' },
      nodes: ['navbar', 'hero', 'stats', 'role', 'platform', 'vision', 'founder', 'faq', 'footer'],
    },

    navbar: {
      type: { resolvedName: 'Navbar' },
      props: {
        logo: '/web-templates/ascent/ascent-icon.svg',
        brandName: 'Ascent',
        links: [
          { label: 'The Role', href: '#role' },
          { label: 'Platform', href: '#platform' },
          { label: 'Vision', href: '#vision' },
          { label: 'Founder', href: '#founder' },
          { label: 'FAQ', href: '#faq' },
        ],
        backgroundColor: INK,
        textColor: '#ffffff',
        sticky: true,
        padding: 18,
        showButton: true,
        buttonText: 'Get In Touch',
        buttonBg: ACCENT,
        buttonTextColor: '#ffffff',
        fullWidth: false,
        borderBottomWidth: 0,
        borderBottomColor: 'transparent',
        linkHoverColor: '#ffffff',
        fontSize: 12,
        fontWeight: '500',
        layoutType: 'side',
        navigationSource: 'none',
        mobileOverlayColor: INK,
        hamburgerColor: '#ffffff',
      },
      parent: 'ROOT',
    },

    hero: {
      type: { resolvedName: 'Hero' },
      isCanvas: true,
      props: {
        layout: 'split',
        heightPreset: 'large',
        backgroundColor: OFF,
        padding: 72,
        padding_mobile: 48,
        padding_tablet: 64,
        gap: 0,
        showBackgroundBlobs: false,
        contentAlignment: 'start',
        contentMaxWidth: 1200,
        useGlassmorphism: false,
        animation: 'fade-in',
        showScrollIndicator: false,
      },
      nodes: ['hero-grid'],
      parent: 'ROOT',
    },
    'hero-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 56, padding: 0, className: 'items-center' },
      nodes: ['hero-left', 'hero-right'],
      parent: 'hero',
    },
    'hero-left': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['hero-badge', 'hero-h', 'hero-p', 'hero-btns'],
      parent: 'hero-grid',
    },
    'hero-badge': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'inline-flex items-center gap-2 bg-white border rounded-full px-4 py-2 mb-6 w-fit', display: 'inline-flex', alignItems: 'center' },
      nodes: ['hero-badge-dot', 'hero-badge-text'],
      parent: 'hero-left',
    },
    'hero-badge-dot': {
      type: { resolvedName: 'Icon' },
      props: { name: 'Circle', size: 8, color: ACCENT, strokeWidth: 0, alignment: 'center', fill: true },
      parent: 'hero-badge',
    },
    'hero-badge-text': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'CO-FOUNDER SEARCH OPEN · EARLY STAGE', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest' },
      parent: 'hero-badge',
    },
    'hero-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'The structural layer this market has never had.', level: 'h1', fontWeight: 'black', color: INK, className: 'text-4xl md:text-6xl leading-[1.1] tracking-tight mb-6' },
      parent: 'hero-left',
    },
    'hero-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'A fast-growing market has a structural blind spot. We built the first tool that addresses it directly — and we’re looking for the technical co-founder to help take it from prototype to product.', fontSize: 18, color: MID, className: 'max-w-xl mb-8' },
      parent: 'hero-left',
    },
    'hero-btns': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex flex-col sm:flex-row gap-4', display: 'flex', flexDirection: 'row', flexDirection_mobile: 'column' },
      nodes: ['hero-btn-1', 'hero-btn-2'],
      parent: 'hero-left',
    },
    'hero-btn-1': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Read The Co-Founder Role', size: 'lg', variant: 'primary', color: INK, textColor: '#ffffff', borderRadius: 4, width: 'fit' },
      parent: 'hero-btns',
    },
    'hero-btn-2': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'See The Platform', size: 'lg', variant: 'outline', color: INK, textColor: INK, borderRadius: 4, width: 'fit' },
      parent: 'hero-btns',
    },
    'hero-right': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'rounded-lg overflow-hidden border shadow-2xl' },
      nodes: ['hero-right-chrome', 'hero-right-img'],
      parent: 'hero-grid',
    },
    'hero-right-chrome': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-center gap-2 px-4 py-3', display: 'flex', alignItems: 'center', backgroundColor: INK },
      nodes: ['hero-chrome-dot-1', 'hero-chrome-dot-2', 'hero-chrome-dot-3'],
      parent: 'hero-right',
    },
    'hero-chrome-dot-1': {
      type: { resolvedName: 'Icon' },
      props: { name: 'Circle', size: 10, color: '#e5645b', strokeWidth: 0, alignment: 'left', fill: true },
      parent: 'hero-right-chrome',
    },
    'hero-chrome-dot-2': {
      type: { resolvedName: 'Icon' },
      props: { name: 'Circle', size: 10, color: '#e0b64d', strokeWidth: 0, alignment: 'left', fill: true },
      parent: 'hero-right-chrome',
    },
    'hero-chrome-dot-3': {
      type: { resolvedName: 'Icon' },
      props: { name: 'Circle', size: 10, color: '#4a8c5c', strokeWidth: 0, alignment: 'left', fill: true },
      parent: 'hero-right-chrome',
    },
    'hero-right-img': {
      type: { resolvedName: 'UserImage' },
      props: { src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop', alt: 'Product dashboard preview', objectFit: 'cover', width: '100%', height: '420px', borderRadius: 0, boxShadow: 'none' },
      parent: 'hero-right',
    },

    stats: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 0, paddingBottom: 0, paddingTop_mobile: 0, paddingBottom_mobile: 0 },
      nodes: ['stats-grid'],
      parent: 'ROOT',
    },
    'stats-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '4', gap: 0, padding: 0 },
      nodes: ['stat-1', 'stat-2', 'stat-3', 'stat-4'],
      parent: 'stats',
    },
    'stat-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r border-b', backgroundColor: '#ffffff' },
      nodes: ['stat-1-lbl', 'stat-1-val'],
      parent: 'stats-grid',
    },
    'stat-1-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'MARKET SIZE · TODAY → 2029', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'stat-1',
    },
    'stat-1-val': {
      type: { resolvedName: 'Heading' },
      props: { text: '$2.4B → $10B', level: 'h3', fontWeight: 'black', color: INK, className: 'text-2xl' },
      parent: 'stat-1',
    },
    'stat-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r border-b', backgroundColor: INK },
      nodes: ['stat-2-lbl', 'stat-2-val'],
      parent: 'stats-grid',
    },
    'stat-2-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'CO-FOUNDER EQUITY', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest mb-2' },
      parent: 'stat-2',
    },
    'stat-2-val': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Meaningful', level: 'h3', fontWeight: 'black', color: '#ffffff', className: 'text-2xl' },
      parent: 'stat-2',
    },
    'stat-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r border-b', backgroundColor: '#ffffff' },
      nodes: ['stat-3-lbl', 'stat-3-val'],
      parent: 'stats-grid',
    },
    'stat-3-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'CORE MODULES AT LAUNCH', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'stat-3',
    },
    'stat-3-val': {
      type: { resolvedName: 'Heading' },
      props: { text: '6', level: 'h3', fontWeight: 'black', color: INK, className: 'text-2xl' },
      parent: 'stat-3',
    },
    'stat-4': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-b', backgroundColor: '#ffffff' },
      nodes: ['stat-4-lbl', 'stat-4-val'],
      parent: 'stats-grid',
    },
    'stat-4-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'CO-FOUNDER RAMP', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'stat-4',
    },
    'stat-4-val': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Flexible', level: 'h3', fontWeight: 'black', color: INK, className: 'text-2xl' },
      parent: 'stat-4',
    },

    role: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: OFF, paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'role' },
      nodes: ['role-inner'],
      parent: 'ROOT',
    },
    'role-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-5xl mx-auto' },
      nodes: ['role-label', 'role-h', 'role-p', 'role-ladder', 'role-card'],
      parent: 'role',
    },
    'role-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'THE ROLE', fontSize: 12, fontWeight: 'bold', color: ACCENT, textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'role-inner',
    },
    'role-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'The hard engineering starts here.', level: 'h2', textAlign: 'center', fontWeight: 'black', color: INK, className: 'text-3xl md:text-5xl mb-6' },
      parent: 'role-inner',
    },
    'role-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'The product vision is documented and a prototype is live. What comes next is genuinely hard, company-defining engineering — and we’re looking for the person who wants to own it.', textAlign: 'center', fontSize: 16, color: MID, className: 'max-w-2xl mx-auto mb-14' },
      parent: 'role-inner',
    },
    'role-ladder': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '3', gap: 0, className: 'border-t border-b mb-14' },
      nodes: ['ladder-1', 'ladder-2', 'ladder-3'],
      parent: 'role-inner',
    },
    'ladder-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-baseline gap-4 p-6 border-r', display: 'flex', alignItems: 'baseline' },
      nodes: ['ladder-1-num', 'ladder-1-text'],
      parent: 'role-ladder',
    },
    'ladder-1-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '01', level: 'h4', fontWeight: 'black', color: '#4a8c5c', className: 'text-lg shrink-0 grow-0 basis-10' },
      parent: 'ladder-1',
    },
    'ladder-1-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['ladder-1-lbl', 'ladder-1-title'],
      parent: 'ladder-1',
    },
    'ladder-1-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'COMPLETE', fontSize: 11, fontWeight: 'bold', color: '#4a8c5c', className: 'uppercase tracking-widest mb-1' },
      parent: 'ladder-1-text',
    },
    'ladder-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Technical Blueprint', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base' },
      parent: 'ladder-1-text',
    },
    'ladder-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-baseline gap-4 p-6 border-r', display: 'flex', alignItems: 'baseline' },
      nodes: ['ladder-2-num', 'ladder-2-text'],
      parent: 'role-ladder',
    },
    'ladder-2-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '02', level: 'h4', fontWeight: 'black', color: '#4a8c5c', className: 'text-lg shrink-0 grow-0 basis-10' },
      parent: 'ladder-2',
    },
    'ladder-2-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['ladder-2-lbl', 'ladder-2-title'],
      parent: 'ladder-2',
    },
    'ladder-2-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'LIVE', fontSize: 11, fontWeight: 'bold', color: '#4a8c5c', className: 'uppercase tracking-widest mb-1' },
      parent: 'ladder-2-text',
    },
    'ladder-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Interactive Prototype', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base' },
      parent: 'ladder-2-text',
    },
    'ladder-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-baseline gap-4 p-6', display: 'flex', alignItems: 'baseline' },
      nodes: ['ladder-3-num', 'ladder-3-text'],
      parent: 'role-ladder',
    },
    'ladder-3-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '03', level: 'h4', fontWeight: 'black', color: ACCENT, className: 'text-lg shrink-0 grow-0 basis-10' },
      parent: 'ladder-3',
    },
    'ladder-3-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['ladder-3-lbl', 'ladder-3-title'],
      parent: 'ladder-3',
    },
    'ladder-3-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: '• NOW', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest mb-1' },
      parent: 'ladder-3-text',
    },
    'ladder-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'MVP Build', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base' },
      parent: 'ladder-3-text',
    },
    'role-card': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border rounded p-10 md:p-12' },
      nodes: ['role-card-head', 'role-own-label', 'role-own-grid', 'role-split'],
      parent: 'role-inner',
    },
    'role-card-head': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      // Always stacked (title block, then button) rather than a responsive row-on-desktop/
      // column-on-mobile flex layout. A row layout here relies on `flexDirection_mobile`,
      // which only takes effect via a real `@media (max-width:768px)` query — the editor's
      // Desktop/Tablet/Mobile toggle narrows a wrapper div at the real (wide) browser width,
      // so that query never fires there while Tailwind's `sm:flex-row` (keyed to the same
      // real width) still does. The row layout then persists in the "mobile" preview with a
      // fixed-width button competing with the title for space, and shrinking the title's
      // flex-basis below its content collapses it into a one-character-per-line column.
      // Stacking unconditionally sidesteps the whole breakpoint mismatch and looks correct
      // at every real width and in every editor preview mode.
      props: { className: 'mb-8 pb-7 border-b' },
      nodes: ['role-card-title-wrap', 'role-card-btn'],
      parent: 'role-card',
    },
    'role-card-title-wrap': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'mb-5' },
      nodes: ['role-card-eyebrow', 'role-card-title'],
      parent: 'role-card-head',
    },
    'role-card-eyebrow': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'ACTIVELY RECRUITING', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest mb-2' },
      parent: 'role-card-title-wrap',
    },
    'role-card-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Technical Co-Founder / CTO', level: 'h3', fontWeight: 'black', color: INK, className: 'text-2xl md:text-3xl' },
      parent: 'role-card-title-wrap',
    },
    'role-card-btn': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Apply For This Role', size: 'md', variant: 'primary', color: INK, textColor: '#ffffff', borderRadius: 4, width: 'fit' },
      parent: 'role-card-head',
    },
    'role-own-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: "WHAT YOU'D OWN", fontSize: 12, fontWeight: 'bold', color: ACCENT, className: 'tracking-widest uppercase mb-4' },
      parent: 'role-card',
    },
    'role-own-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 16, className: 'mb-8' },
      nodes: ['own-1', 'own-2', 'own-3', 'own-4'],
      parent: 'role-card',
    },
    'own-1': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Core product architecture — the shared engine every feature is built on, not five disconnected tools.', fontSize: 15, color: MID },
      parent: 'role-own-grid',
    },
    'own-2': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Multi-model orchestration and the data pipeline that lets the product get smarter the more it’s used.', fontSize: 15, color: MID },
      parent: 'role-own-grid',
    },
    'own-3': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Fairness and quality review built into the architecture from day one, not bolted on later.', fontSize: 15, color: MID },
      parent: 'role-own-grid',
    },
    'own-4': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Production infrastructure, hiring, and every major technical decision as we scale.', fontSize: 15, color: MID },
      parent: 'role-own-grid',
    },
    'role-split': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 40, className: 'pt-7 border-t' },
      nodes: ['role-looking', 'role-terms'],
      parent: 'role-card',
    },
    'role-looking': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['role-looking-label', 'role-looking-p', 'role-tags'],
      parent: 'role-split',
    },
    'role-looking-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: "WHAT WE'RE LOOKING FOR", fontSize: 12, fontWeight: 'bold', color: ACCENT, className: 'tracking-widest uppercase mb-3' },
      parent: 'role-looking',
    },
    'role-looking-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'You’ve shipped production AI systems — not just trained a model, but taken one to real users. You see a gap this size and already think in terms of the system you’d build to fill it.', fontSize: 15, color: MID, className: 'mb-4' },
      parent: 'role-looking',
    },
    'role-tags': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex flex-wrap gap-2', display: 'flex' },
      nodes: ['tag-1', 'tag-2', 'tag-3', 'tag-4'],
      parent: 'role-looking',
    },
    'tag-1': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Production AI / ML', fontSize: 12, color: INK, className: 'px-3 py-1 border rounded-full' },
      parent: 'role-tags',
    },
    'tag-2': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'NLP / LLM', fontSize: 12, color: INK, className: 'px-3 py-1 border rounded-full' },
      parent: 'role-tags',
    },
    'tag-3': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Systems Architecture', fontSize: 12, color: INK, className: 'px-3 py-1 border rounded-full' },
      parent: 'role-tags',
    },
    'tag-4': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Shipped Products', fontSize: 12, color: INK, className: 'px-3 py-1 border rounded-full' },
      parent: 'role-tags',
    },
    'role-terms': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['role-terms-label', 'role-term-1', 'role-term-2', 'role-term-3'],
      parent: 'role-split',
    },
    'role-terms-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'TERMS', fontSize: 12, fontWeight: 'bold', color: ACCENT, className: 'tracking-widest uppercase mb-3' },
      parent: 'role-terms',
    },
    'role-term-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'pb-3 mb-3 border-b' },
      nodes: ['role-term-1-lbl', 'role-term-1-val'],
      parent: 'role-terms',
    },
    'role-term-1-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'EQUITY', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-1' },
      parent: 'role-term-1',
    },
    'role-term-1-val': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Meaningful co-founder equity. Standard 4-year vest, 1-year cliff.', fontSize: 14, color: INK },
      parent: 'role-term-1',
    },
    'role-term-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'pb-3 mb-3 border-b' },
      nodes: ['role-term-2-lbl', 'role-term-2-val'],
      parent: 'role-terms',
    },
    'role-term-2-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'COMMITMENT', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-1' },
      parent: 'role-term-2',
    },
    'role-term-2-val': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Part-time start, full-time tied to mutual readiness.', fontSize: 14, color: INK },
      parent: 'role-term-2',
    },
    'role-term-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['role-term-3-lbl', 'role-term-3-val'],
      parent: 'role-terms',
    },
    'role-term-3-lbl': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'LOCATION', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-1' },
      parent: 'role-term-3',
    },
    'role-term-3-val': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Remote-friendly, US-based preferred.', fontSize: 14, color: INK },
      parent: 'role-term-3',
    },

    platform: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 60, paddingTop_mobile: 60, paddingBottom_mobile: 40, id: 'platform' },
      nodes: ['platform-inner'],
      parent: 'ROOT',
    },
    'platform-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['platform-top', 'platform-grid'],
      parent: 'platform',
    },
    'platform-top': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 48, className: 'items-center pb-12 mb-12 border-b' },
      nodes: ['platform-h-wrap', 'platform-sub'],
      parent: 'platform-inner',
    },
    'platform-h-wrap': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['platform-label', 'platform-h'],
      parent: 'platform-top',
    },
    'platform-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'THE PLATFORM', fontSize: 12, fontWeight: 'bold', color: ACCENT, className: 'tracking-widest uppercase mb-3' },
      parent: 'platform-h-wrap',
    },
    'platform-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Six capabilities no single tool has combined.', level: 'h2', fontWeight: 'black', color: INK, className: 'text-3xl md:text-4xl' },
      parent: 'platform-h-wrap',
    },
    'platform-sub': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Each one addresses a gap the market has left alone. Together they form a category, not a feature list.', fontSize: 16, color: MID },
      parent: 'platform-top',
    },
    'platform-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '3', gap: 0 },
      nodes: ['feat-1', 'feat-2', 'feat-3', 'feat-4', 'feat-5', 'feat-6'],
      parent: 'platform-inner',
    },
    'feat-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r border-b' },
      nodes: ['feat-1-num', 'feat-1-title', 'feat-1-desc'],
      parent: 'platform-grid',
    },
    'feat-1-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'I.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-1',
    },
    'feat-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Structure Map', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-1',
    },
    'feat-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'The whole project mapped visually, so structural problems are visible before you touch a single word.', fontSize: 14, color: MID },
      parent: 'feat-1',
    },
    'feat-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r border-b' },
      nodes: ['feat-2-num', 'feat-2-title', 'feat-2-desc'],
      parent: 'platform-grid',
    },
    'feat-2-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'II.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-2',
    },
    'feat-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'AI Co-Writer', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-2',
    },
    'feat-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Lives inside the document, reads the full context, and drafts real alternatives instead of one-off suggestions.', fontSize: 14, color: MID },
      parent: 'feat-2',
    },
    'feat-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-b' },
      nodes: ['feat-3-num', 'feat-3-title', 'feat-3-desc'],
      parent: 'platform-grid',
    },
    'feat-3-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'III.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-3',
    },
    'feat-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Fairness-Reviewed', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-3',
    },
    'feat-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Every suggestion passes an independent fairness check across multiple dimensions, built in from day one.', fontSize: 14, color: MID },
      parent: 'feat-3',
    },
    'feat-4': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r' },
      nodes: ['feat-4-num', 'feat-4-title', 'feat-4-desc'],
      parent: 'platform-grid',
    },
    'feat-4-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'IV.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-4',
    },
    'feat-4-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Adaptive Learning', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-4',
    },
    'feat-4-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'When a user consistently overrides a suggestion, the system learns and stops flagging it. No settings required.', fontSize: 14, color: MID },
      parent: 'feat-4',
    },
    'feat-5': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8 border-r' },
      nodes: ['feat-5-num', 'feat-5-title', 'feat-5-desc'],
      parent: 'platform-grid',
    },
    'feat-5-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'V.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-5',
    },
    'feat-5-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Cross-Project Memory', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-5',
    },
    'feat-5-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Every new project benefits from everything learned on the last one — intelligence that compounds over time.', fontSize: 14, color: MID },
      parent: 'feat-5',
    },
    'feat-6': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'p-8' },
      nodes: ['feat-6-num', 'feat-6-title', 'feat-6-desc'],
      parent: 'platform-grid',
    },
    'feat-6-num': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'VI.', fontSize: 26, fontWeight: 'black', color: ACCENT, className: 'mb-4 italic' },
      parent: 'feat-6',
    },
    'feat-6-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Stress-Test Mode', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-3' },
      parent: 'feat-6',
    },
    'feat-6-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Before you ship, the system attacks its own output as a skeptical reviewer would — so you find the gaps first.', fontSize: 14, color: MID },
      parent: 'feat-6',
    },

    vision: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: OFF, paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'vision' },
      nodes: ['vision-inner'],
      parent: 'ROOT',
    },
    'vision-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['vision-label', 'vision-h', 'vision-p', 'roadmap-grid', 'domain-grid'],
      parent: 'vision',
    },
    'vision-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'THE BIGGER PICTURE', fontSize: 12, fontWeight: 'bold', color: ACCENT, className: 'tracking-widest uppercase mb-3' },
      parent: 'vision-inner',
    },
    'vision-h': {
      type: { resolvedName: 'Heading' },
      props: { text: "This category is where we start. It's not where we stop.", level: 'h2', fontWeight: 'black', color: INK, className: 'text-3xl md:text-4xl mb-4' },
      parent: 'vision-inner',
    },
    'vision-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'The beachhead segment gives us the clearest need and the fastest signal. The same core engine expands into adjacent markets over time.', fontSize: 16, color: MID, className: 'max-w-2xl mb-12' },
      parent: 'vision-inner',
    },
    'roadmap-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '3', gap: 24, className: 'mb-14' },
      nodes: ['road-1', 'road-2', 'road-3'],
      parent: 'vision-inner',
    },
    'road-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border-l-4 rounded p-6', borderColor: '#4a8c5c', borderWidth: 4, borderStyle: 'solid' },
      nodes: ['road-1-dot', 'road-1-title', 'road-1-desc'],
      parent: 'roadmap-grid',
    },
    'road-1-dot': {
      type: { resolvedName: 'Paragraph' },
      props: { text: '✓ COMPLETE', fontSize: 11, fontWeight: 'bold', color: '#4a8c5c', className: 'uppercase tracking-widest mb-2' },
      parent: 'road-1',
    },
    'road-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Blueprint & Prototype', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base mb-1' },
      parent: 'road-1',
    },
    'road-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Technical blueprint finished; interactive prototype live and demoable.', fontSize: 13, color: MID },
      parent: 'road-1',
    },
    'road-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border-l-4 rounded p-6', borderColor: ACCENT, borderWidth: 4, borderStyle: 'solid' },
      nodes: ['road-2-dot', 'road-2-title', 'road-2-desc'],
      parent: 'roadmap-grid',
    },
    'road-2-dot': {
      type: { resolvedName: 'Paragraph' },
      props: { text: '• NOW', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest mb-2' },
      parent: 'road-2',
    },
    'road-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'MVP & Beta', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base mb-1' },
      parent: 'road-2',
    },
    'road-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Self-funded build underway; closed beta with early users next.', fontSize: 13, color: MID },
      parent: 'road-2',
    },
    'road-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border-l-4 rounded p-6', borderColor: '#d9d3c7', borderWidth: 4, borderStyle: 'solid' },
      nodes: ['road-3-dot', 'road-3-title', 'road-3-desc'],
      parent: 'roadmap-grid',
    },
    'road-3-dot': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'NEXT', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'road-3',
    },
    'road-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Seed & Series A', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base mb-1' },
      parent: 'road-3',
    },
    'road-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Raise to build the team, expand the model, and open new segments.', fontSize: 13, color: MID },
      parent: 'road-3',
    },
    'domain-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '3', gap: 16 },
      nodes: ['domain-1', 'domain-2', 'domain-3'],
      parent: 'vision-inner',
    },
    'domain-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'rounded p-6', backgroundColor: INK },
      nodes: ['domain-1-phase', 'domain-1-name', 'domain-1-desc'],
      parent: 'domain-grid',
    },
    'domain-1-phase': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'LAUNCH · BEACHHEAD', fontSize: 11, fontWeight: 'bold', color: ACCENT, className: 'uppercase tracking-widest mb-2' },
      parent: 'domain-1',
    },
    'domain-1-name': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Primary Segment', level: 'h4', fontWeight: 'black', color: '#ffffff', className: 'text-lg mb-2' },
      parent: 'domain-1',
    },
    'domain-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'The clearest need and fastest path to real usage data — where the product proves itself first.', fontSize: 13, color: 'rgba(255,255,255,0.7)' },
      parent: 'domain-1',
    },
    'domain-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border rounded p-6' },
      nodes: ['domain-2-phase', 'domain-2-name', 'domain-2-desc'],
      parent: 'domain-grid',
    },
    'domain-2-phase': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'SERIES A · EXPANSION', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'domain-2',
    },
    'domain-2-name': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Adjacent Market A', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-2' },
      parent: 'domain-2',
    },
    'domain-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Same core engine, tuned for a second professional segment with its own workflow.', fontSize: 13, color: MID },
      parent: 'domain-2',
    },
    'domain-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'bg-white border rounded p-6' },
      nodes: ['domain-3-phase', 'domain-3-name', 'domain-3-desc'],
      parent: 'domain-grid',
    },
    'domain-3-phase': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'SERIES B · ENTERPRISE', fontSize: 11, fontWeight: 'bold', color: MID, className: 'uppercase tracking-widest mb-2' },
      parent: 'domain-3',
    },
    'domain-3-name': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Enterprise Tier', level: 'h4', fontWeight: 'black', color: INK, className: 'text-lg mb-2' },
      parent: 'domain-3',
    },
    'domain-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Compliance, team collaboration, and cross-document intelligence for larger organizations.', fontSize: 13, color: MID },
      parent: 'domain-3',
    },

    founder: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'founder' },
      nodes: ['founder-inner'],
      parent: 'ROOT',
    },
    'founder-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-5xl mx-auto' },
      nodes: ['founder-label', 'founder-grid'],
      parent: 'founder',
    },
    'founder-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'FOUNDER', fontSize: 12, fontWeight: 'bold', color: ACCENT, textAlign: 'center', className: 'tracking-widest uppercase mb-10' },
      parent: 'founder-inner',
    },
    'founder-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '1/3-2/3', gap: 56, className: 'items-start' },
      nodes: ['founder-photo', 'founder-text'],
      parent: 'founder-inner',
    },
    'founder-photo': {
      type: { resolvedName: 'UserImage' },
      props: { src: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop', alt: 'Founder portrait', objectFit: 'cover', width: '100%', height: '340px', borderRadius: 4, boxShadow: 'none' },
      parent: 'founder-grid',
    },
    'founder-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['founder-h', 'founder-p1', 'founder-p2', 'founder-p3', 'founder-name'],
      parent: 'founder-grid',
    },
    'founder-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'I hit the same wall myself — so I designed the way through it.', level: 'h3', fontWeight: 'black', color: INK, className: 'text-2xl md:text-3xl mb-6' },
      parent: 'founder-text',
    },
    'founder-p1': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'I spent years deep in a project I knew intimately — every detail, every decision — and still couldn’t see the shape of the whole thing. That loss of perspective is common, and every tool I tried made me faster without ever making the structure visible.', fontSize: 15, color: MID, className: 'mb-4' },
      parent: 'founder-text',
    },
    'founder-p2': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'So I built the tool I wished existed: something that maps the whole structure of a project, not just fragments of it, without taking over the judgment calls that are mine to make.', fontSize: 15, color: MID, className: 'mb-4' },
      parent: 'founder-text',
    },
    'founder-p3': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'That single problem, solved well, turned out to generalize far beyond where I first found it.', fontSize: 15, color: MID, className: 'mb-6' },
      parent: 'founder-text',
    },
    'founder-name': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Alex Rivera, Founder', level: 'h4', fontWeight: 'bold', color: INK, className: 'text-base' },
      parent: 'founder-text',
    },

    faq: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: INK, paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'faq' },
      nodes: ['faq-inner'],
      parent: 'ROOT',
    },
    'faq-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-5xl mx-auto' },
      nodes: ['faq-label', 'faq-h', 'faq-block'],
      parent: 'faq',
    },
    'faq-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'FAQ', fontSize: 12, fontWeight: 'bold', color: ACCENT, textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'faq-inner',
    },
    'faq-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'For co-founder candidates', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#ffffff', className: 'text-3xl md:text-4xl mb-12' },
      parent: 'faq-inner',
    },
    'faq-block': {
      type: { resolvedName: 'FAQ' },
      props: {
        items: [
          { question: 'Why this segment first?', answer: 'It has the clearest unmet need, the strongest early-adopter community, and gives us the fastest path to real usage data — the same core engine expands from there.' },
          { question: "What's the funding plan?", answer: 'Bootstrapped through the current build phase, then a seed round to fund the engineering team and domain-specific model training once the MVP and a technical co-founder are in place.' },
          { question: 'How do equity and IP work?', answer: 'Both negotiated with counsel, not pre-set. Meaningful co-founder equity on a standard four-year vest with a one-year cliff; all company IP is owned by the company from incorporation.' },
          { question: "What's the competitive moat?", answer: 'Proprietary training data compounding over time, a technical architecture that’s hard to replicate quickly, and UI paradigms with no direct equivalent in the market today.' },
          { question: "What's the current stage, in one line?", answer: 'Blueprint complete, interactive prototype live, MVP in active development, co-founder search open.' },
        ],
        itemBg: 'rgba(255,255,255,0.04)',
        borderColor: 'rgba(255,255,255,0.12)',
        questionColor: '#ffffff',
        answerColor: 'rgba(255,255,255,0.7)',
        iconColor: ACCENT,
        borderRadius: 8,
        gap: 12,
        padding: 24,
      },
      parent: 'faq-inner',
    },

    footer: {
      type: { resolvedName: 'Footer' },
      props: {
        logo: '/web-templates/ascent/ascent-icon.svg',
        brandName: 'Ascent',
        description: 'Building the structural layer this market has never had.',
        columns: [
          { title: 'Company', links: [{ label: 'The Role', href: '#role' }, { label: 'Platform', href: '#platform' }, { label: 'Vision', href: '#vision' }, { label: 'Founder', href: '#founder' }] },
          { title: 'Resources', links: [{ label: 'FAQ', href: '#faq' }, { label: 'Contact', href: '#' }, { label: 'Privacy Policy', href: '#' }] },
        ],
        backgroundColor: INK,
        textColor: '#ffffff',
        accentColor: ACCENT,
        padding: 60,
        fullWidth: false,
        columnsCount: 2,
        showSocial: true,
        socialLinks: [
          { platform: 'twitter', url: '#' },
          { platform: 'linkedin', url: '#' },
        ],
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        titleFontSize: 12,
        linkFontSize: 14,
        titleFontWeight: '900',
        showNewsletter: false,
        newsletterTitle: '',
        newsletterDescription: '',
      },
      parent: 'ROOT',
    },
  }),
};
