import { BuilderTemplate } from '../templates';

export const mentor: BuilderTemplate = {
  id: 'mentor',
  name: 'Mentor',
  description: 'Warm, approachable homepage for coaches and course creators, with mentorship-driven copy, live stats, pricing, and testimonials.',
  category: 'Education',
  type: 'both',
  step_type: 'sales_page',
  is_premium: true,
  // A real screenshot of this template's own rendered hero (public/web-templates/mentor/).
  thumbnail: '/web-templates/mentor/thumbnail.jpg',
  content: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'min-h-screen bg-white text-slate-900' },
      nodes: ['navbar', 'hero', 'features', 'stats', 'about', 'cta', 'process', 'pricing', 'testimonials', 'contact', 'blog', 'footer'],
    },

    navbar: {
      type: { resolvedName: 'Navbar' },
      props: {
        logo: '/web-templates/mentor/mentor-icon.svg',
        brandName: 'Mentor',
        links: [
          { label: 'About', href: '#about' },
          { label: 'Pricing', href: '#pricing' },
          { label: 'Testimonials', href: '#testimonials' },
          { label: 'Blog', href: '#blog' },
          { label: 'Contact', href: '#contact' },
        ],
        backgroundColor: '#ffffff',
        textColor: '#0f172a',
        sticky: true,
        padding: 20,
        showButton: true,
        buttonText: 'Get Started',
        buttonBg: '#0d9488',
        buttonTextColor: '#ffffff',
        fullWidth: false,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        linkHoverColor: '#0d9488',
        fontSize: 12,
        fontWeight: '600',
        layoutType: 'side',
        navigationSource: 'none',
        mobileOverlayColor: '#ffffff',
        hamburgerColor: '#0f172a',
      },
      parent: 'ROOT',
    },

    hero: {
      type: { resolvedName: 'Hero' },
      isCanvas: true,
      props: {
        layout: 'split',
        heightPreset: 'large',
        backgroundColor: '#f8fafc',
        padding: 72,
        padding_mobile: 48,
        padding_tablet: 64,
        gap: 0,
        showBackgroundBlobs: true,
        contentAlignment: 'start',
        contentMaxWidth: 1200,
        useGlassmorphism: false,
        animation: 'fade-in',
        showScrollIndicator: false,
      },
      nodes: ['hero-grid'],
      parent: 'ROOT',
    },
    'hero-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 56, padding: 0, className: 'items-center' },
      nodes: ['hero-left', 'hero-right'],
      parent: 'hero',
    },
    'hero-left': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['hero-badge', 'hero-h', 'hero-p', 'hero-btns'],
      parent: 'hero-grid',
    },
    'hero-badge': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'inline-flex items-center gap-2 rounded-full px-4 py-2 mb-6 w-fit', display: 'inline-flex', flexDirection: 'row', alignItems: 'center', backgroundColor: '#f0fdfa' },
      nodes: ['hero-badge-dot', 'hero-badge-text'],
      parent: 'hero-left',
    },
    'hero-badge-dot': {
      type: { resolvedName: 'Icon' },
      props: { name: 'GraduationCap', size: 14, color: '#0d9488', strokeWidth: 2, alignment: 'center' },
      parent: 'hero-badge',
    },
    'hero-badge-text': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'WELCOME TO ONLINE COACHING', fontSize: 11, fontWeight: 'bold', color: '#0d9488', className: 'uppercase tracking-widest' },
      parent: 'hero-badge',
    },
    'hero-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'From Beginner To Pro — With The Right Mentor.', level: 'h1', fontWeight: 'black', color: '#0f172a', className: 'text-4xl md:text-6xl leading-[1.05] tracking-tight mb-6' },
      parent: 'hero-left',
    },
    'hero-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Personalized coaching and expertly designed courses to help you build real skills, at your own pace, with guidance every step of the way.', fontSize: 18, color: '#475569', className: 'max-w-xl mb-8' },
      parent: 'hero-left',
    },
    'hero-btns': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex flex-col sm:flex-row gap-4', display: 'flex', flexDirection: 'row', flexDirection_mobile: 'column' },
      nodes: ['hero-btn-1', 'hero-btn-2'],
      parent: 'hero-left',
    },
    'hero-btn-1': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Get Started', size: 'lg', variant: 'primary', color: '#0d9488', textColor: '#ffffff', borderRadius: 999, width: 'fit' },
      parent: 'hero-btns',
    },
    'hero-btn-2': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Learn More', size: 'lg', variant: 'outline', color: '#0f172a', textColor: '#0f172a', borderRadius: 999, width: 'fit' },
      parent: 'hero-btns',
    },
    'hero-right': {
      type: { resolvedName: 'UserImage' },
      props: { src: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1200&auto=format&fit=crop', alt: 'Mentor guiding a student through a lesson', objectFit: 'cover', width: '100%', height: '480px', borderRadius: 24, boxShadow: 'xl' },
      parent: 'hero-grid',
    },

    features: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 60, paddingTop_mobile: 60, paddingBottom_mobile: 40 },
      nodes: ['features-inner'],
      parent: 'ROOT',
    },
    'features-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['features-label', 'features-h', 'features-p', 'features-grid'],
      parent: 'features',
    },
    'features-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'WHY CHOOSE MENTOR', fontSize: 12, fontWeight: 'bold', color: '#0d9488', textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'features-inner',
    },
    'features-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'So Many Reasons To Start', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-5xl mb-4' },
      parent: 'features-inner',
    },
    'features-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Start, switch, or advance your skills with expertly guided courses and mentorship built around real outcomes.', textAlign: 'center', fontSize: 16, color: '#64748b', className: 'max-w-2xl mx-auto mb-14' },
      parent: 'features-inner',
    },
    'features-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '3', gap: 32 },
      nodes: ['feat-col-1', 'feat-col-2', 'feat-col-3'],
      parent: 'features-inner',
    },
    'feat-col-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'text-center md:text-left' },
      nodes: ['feat-col-1-iconbox', 'feat-col-1-title', 'feat-col-1-desc'],
      parent: 'features-grid',
    },
    'feat-col-1-iconbox': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'w-14 h-14 rounded-2xl flex items-center justify-center mb-5 mx-auto md:mx-0', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f0fdfa' },
      nodes: ['feat-col-1-icon'],
      parent: 'feat-col-1',
    },
    'feat-col-1-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'GraduationCap', size: 24, color: '#0d9488', strokeWidth: 2, alignment: 'center' },
      parent: 'feat-col-1-iconbox',
    },
    'feat-col-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Highly Experienced', level: 'h3', fontWeight: 'black', color: '#0f172a', className: 'text-xl mb-3' },
      parent: 'feat-col-1',
    },
    'feat-col-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Learn from mentors who bring real, hands-on experience and a genuine passion for helping others grow.', fontSize: 15, color: '#64748b' },
      parent: 'feat-col-1',
    },
    'feat-col-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'text-center md:text-left' },
      nodes: ['feat-col-2-iconbox', 'feat-col-2-title', 'feat-col-2-desc'],
      parent: 'features-grid',
    },
    'feat-col-2-iconbox': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'w-14 h-14 rounded-2xl flex items-center justify-center mb-5 mx-auto md:mx-0', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f0fdfa' },
      nodes: ['feat-col-2-icon'],
      parent: 'feat-col-2',
    },
    'feat-col-2-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'Lightbulb', size: 24, color: '#0d9488', strokeWidth: 2, alignment: 'center' },
      parent: 'feat-col-2-iconbox',
    },
    'feat-col-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Innovative Approach', level: 'h3', fontWeight: 'black', color: '#0f172a', className: 'text-xl mb-3' },
      parent: 'feat-col-2',
    },
    'feat-col-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Interactive lessons and creative teaching methods keep every session engaging and effective.', fontSize: 15, color: '#64748b' },
      parent: 'feat-col-2',
    },
    'feat-col-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'text-center md:text-left' },
      nodes: ['feat-col-3-iconbox', 'feat-col-3-title', 'feat-col-3-desc'],
      parent: 'features-grid',
    },
    'feat-col-3-iconbox': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'w-14 h-14 rounded-2xl flex items-center justify-center mb-5 mx-auto md:mx-0', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f0fdfa' },
      nodes: ['feat-col-3-icon'],
      parent: 'feat-col-3',
    },
    'feat-col-3-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'TrendingUp', size: 24, color: '#0d9488', strokeWidth: 2, alignment: 'center' },
      parent: 'feat-col-3-iconbox',
    },
    'feat-col-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Proven Results', level: 'h3', fontWeight: 'black', color: '#0f172a', className: 'text-xl mb-3' },
      parent: 'feat-col-3',
    },
    'feat-col-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Progress is tracked and methods are refined continuously to make sure you actually reach your goals.', fontSize: 15, color: '#64748b' },
      parent: 'feat-col-3',
    },

    stats: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#0f172a', paddingTop: 80, paddingBottom: 80, paddingTop_mobile: 50, paddingBottom_mobile: 50 },
      nodes: ['stats-inner'],
      parent: 'ROOT',
    },
    'stats-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['stats-counter'],
      parent: 'stats',
    },
    'stats-counter': {
      type: { resolvedName: 'StatCounter' },
      props: {
        stats: [
          { value: 3900, suffix: '+', label: 'Students Enrolled' },
          { value: 1200, suffix: '+', label: 'Active Courses' },
          { value: 850, suffix: '+', label: 'Qualified Mentors' },
          { value: 5500, suffix: '+', label: 'Course Completions' },
        ],
        numberColor: '#ffffff',
        labelColor: '#94a3b8',
        accentColor: '#2dd4bf',
        backgroundColor: 'transparent',
        duration: 2.5,
      },
      parent: 'stats-inner',
    },

    about: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#f8fafc', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'about' },
      nodes: ['about-inner'],
      parent: 'ROOT',
    },
    'about-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['about-grid'],
      parent: 'about',
    },
    'about-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 64, className: 'items-center' },
      nodes: ['about-left', 'about-right'],
      parent: 'about-inner',
    },
    'about-left': {
      type: { resolvedName: 'UserImage' },
      props: { src: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1000&auto=format&fit=crop', alt: 'Mentor helping a student learn', objectFit: 'cover', width: '100%', height: '460px', borderRadius: 24, boxShadow: 'lg' },
      parent: 'about-grid',
    },
    'about-right': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['about-label', 'about-h', 'about-p', 'about-bullets', 'about-btn'],
      parent: 'about-grid',
    },
    'about-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'GET TO KNOW ABOUT US', fontSize: 12, fontWeight: 'bold', color: '#0d9488', className: 'tracking-widest uppercase mb-3' },
      parent: 'about-right',
    },
    'about-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'A Smarter Way To Learn In The Digital World', level: 'h2', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-4xl mb-4' },
      parent: 'about-right',
    },
    'about-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Our programs are designed to match your goals, interests, and pace, combining structured lessons with one-on-one mentorship for real, lasting progress.', fontSize: 16, color: '#475569', className: 'mb-8' },
      parent: 'about-right',
    },
    'about-bullets': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 20, padding: 0, className: 'mb-8' },
      nodes: ['about-bullet-1', 'about-bullet-2', 'about-bullet-3'],
      parent: 'about-right',
    },
    'about-bullet-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-3', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['about-bullet-1-icon', 'about-bullet-1-text'],
      parent: 'about-bullets',
    },
    'about-bullet-1-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'CheckCircle2', size: 20, color: '#0d9488', strokeWidth: 2, alignment: 'left', className: 'mt-0.5 shrink-0' },
      parent: 'about-bullet-1',
    },
    'about-bullet-1-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['about-bullet-1-title', 'about-bullet-1-desc'],
      parent: 'about-bullet-1',
    },
    'about-bullet-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Flexible Scheduling', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-base mb-1' },
      parent: 'about-bullet-1-text',
    },
    'about-bullet-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Sessions and courses that fit around your life, not the other way around.', fontSize: 13, color: '#64748b' },
      parent: 'about-bullet-1-text',
    },
    'about-bullet-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-3', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['about-bullet-2-icon', 'about-bullet-2-text'],
      parent: 'about-bullets',
    },
    'about-bullet-2-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'CheckCircle2', size: 20, color: '#0d9488', strokeWidth: 2, alignment: 'left', className: 'mt-0.5 shrink-0' },
      parent: 'about-bullet-2',
    },
    'about-bullet-2-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['about-bullet-2-title', 'about-bullet-2-desc'],
      parent: 'about-bullet-2',
    },
    'about-bullet-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Verified Certificates', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-base mb-1' },
      parent: 'about-bullet-2-text',
    },
    'about-bullet-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Earn a shareable certificate for every course and track you complete.', fontSize: 13, color: '#64748b' },
      parent: 'about-bullet-2-text',
    },
    'about-bullet-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-3', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['about-bullet-3-icon', 'about-bullet-3-text'],
      parent: 'about-bullets',
    },
    'about-bullet-3-icon': {
      type: { resolvedName: 'Icon' },
      props: { name: 'CheckCircle2', size: 20, color: '#0d9488', strokeWidth: 2, alignment: 'left', className: 'mt-0.5 shrink-0' },
      parent: 'about-bullet-3',
    },
    'about-bullet-3-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['about-bullet-3-title', 'about-bullet-3-desc'],
      parent: 'about-bullet-3',
    },
    'about-bullet-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Expert Mentors', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-base mb-1' },
      parent: 'about-bullet-3-text',
    },
    'about-bullet-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Every mentor is vetted for real-world experience, not just credentials.', fontSize: 13, color: '#64748b' },
      parent: 'about-bullet-3-text',
    },
    'about-btn': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'More About Us', size: 'md', variant: 'primary', color: '#0d9488', textColor: '#ffffff', borderRadius: 999, width: 'fit' },
      parent: 'about-right',
    },

    cta: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#0f172a', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60 },
      nodes: ['cta-inner'],
      parent: 'ROOT',
    },
    'cta-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-3xl mx-auto text-center' },
      nodes: ['cta-h', 'cta-p', 'cta-btns'],
      parent: 'cta',
    },
    'cta-h': {
      type: { resolvedName: 'Heading' },
      props: { text: '50% Off For The First 50 Students & Mentors', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#ffffff', className: 'text-3xl md:text-5xl leading-tight mb-6' },
      parent: 'cta-inner',
    },
    'cta-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Get unlimited access to thousands of expert-led courses and mentorship sessions for your whole team.', textAlign: 'center', fontSize: 17, color: '#94a3b8', className: 'max-w-xl mx-auto mb-10' },
      parent: 'cta-inner',
    },
    'cta-btns': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex flex-col sm:flex-row gap-4 justify-center', display: 'flex', flexDirection: 'row', justifyContent: 'center', flexDirection_mobile: 'column' },
      nodes: ['cta-btn-1', 'cta-btn-2'],
      parent: 'cta-inner',
    },
    'cta-btn-1': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Join With Us', size: 'lg', variant: 'primary', color: '#2dd4bf', textColor: '#0f172a', borderRadius: 999, width: 'fit' },
      parent: 'cta-btns',
    },
    'cta-btn-2': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Become A Mentor', size: 'lg', variant: 'outline', color: '#ffffff', textColor: '#ffffff', borderRadius: 999, width: 'fit' },
      parent: 'cta-btns',
    },

    process: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60 },
      nodes: ['process-grid'],
      parent: 'ROOT',
    },
    'process-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 64, className: 'items-start' },
      nodes: ['process-left', 'process-right'],
      parent: 'process',
    },
    'process-left': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: '' },
      nodes: ['process-label', 'process-h', 'process-p', 'process-btn'],
      parent: 'process-grid',
    },
    'process-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: "LET'S BEGIN", fontSize: 12, fontWeight: 'bold', color: '#0d9488', className: 'tracking-widest uppercase mb-3' },
      parent: 'process-left',
    },
    'process-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'How To Begin As A Mentee', level: 'h2', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-4xl mb-4' },
      parent: 'process-left',
    },
    'process-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Getting started is simple. Set your goals, connect with a mentor, and follow a structured plan built around measurable progress.', fontSize: 16, color: '#475569', className: 'mb-8' },
      parent: 'process-left',
    },
    'process-btn': {
      type: { resolvedName: 'UserButton' },
      props: { text: 'Get Started', size: 'md', variant: 'primary', color: '#0d9488', textColor: '#ffffff', borderRadius: 999, width: 'fit' },
      parent: 'process-left',
    },
    'process-right': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'space-y-8' },
      nodes: ['process-step-1', 'process-step-2', 'process-step-3'],
      parent: 'process-grid',
    },
    'process-step-1': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-5', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['process-step-1-num', 'process-step-1-text'],
      parent: 'process-right',
    },
    'process-step-1-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '1', level: 'h3', fontWeight: 'black', color: '#0d9488', className: 'text-3xl shrink-0 grow-0 basis-10' },
      parent: 'process-step-1',
    },
    'process-step-1-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['process-step-1-title', 'process-step-1-desc'],
      parent: 'process-step-1',
    },
    'process-step-1-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Plan Your Path', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-lg mb-2' },
      parent: 'process-step-1-text',
    },
    'process-step-1-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Define what you want to learn and set milestones that keep you accountable and motivated.', fontSize: 14, color: '#64748b' },
      parent: 'process-step-1-text',
    },
    'process-step-2': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-5', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['process-step-2-num', 'process-step-2-text'],
      parent: 'process-right',
    },
    'process-step-2-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '2', level: 'h3', fontWeight: 'black', color: '#0d9488', className: 'text-3xl shrink-0 grow-0 basis-10' },
      parent: 'process-step-2',
    },
    'process-step-2-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['process-step-2-title', 'process-step-2-desc'],
      parent: 'process-step-2',
    },
    'process-step-2-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Start Learning', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-lg mb-2' },
      parent: 'process-step-2-text',
    },
    'process-step-2-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Work through structured lessons and live sessions guided by an experienced mentor.', fontSize: 14, color: '#64748b' },
      parent: 'process-step-2-text',
    },
    'process-step-3': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex items-start gap-5', display: 'flex', flexDirection: 'row', alignItems: 'flex-start' },
      nodes: ['process-step-3-num', 'process-step-3-text'],
      parent: 'process-right',
    },
    'process-step-3-num': {
      type: { resolvedName: 'Heading' },
      props: { text: '3', level: 'h3', fontWeight: 'black', color: '#0d9488', className: 'text-3xl shrink-0 grow-0 basis-10' },
      parent: 'process-step-3',
    },
    'process-step-3-text': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'flex-1 min-w-0' },
      nodes: ['process-step-3-title', 'process-step-3-desc'],
      parent: 'process-step-3',
    },
    'process-step-3-title': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Track Your Growth', level: 'h4', fontWeight: 'black', color: '#0f172a', className: 'text-lg mb-2' },
      parent: 'process-step-3-text',
    },
    'process-step-3-desc': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Review progress regularly and adjust your plan to keep moving toward your goals.', fontSize: 14, color: '#64748b' },
      parent: 'process-step-3-text',
    },

    pricing: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#f8fafc', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'pricing' },
      nodes: ['pricing-inner'],
      parent: 'ROOT',
    },
    'pricing-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['pricing-label', 'pricing-h', 'pricing-table'],
      parent: 'pricing',
    },
    'pricing-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'MENTORSHIP PROGRAMS & PLANS', fontSize: 12, fontWeight: 'bold', color: '#0d9488', textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'pricing-inner',
    },
    'pricing-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Pricing Built Around Your Goals', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-5xl mb-12' },
      parent: 'pricing-inner',
    },
    'pricing-table': {
      type: { resolvedName: 'PricingTable' },
      props: {
        enableBillingToggle: true,
        monthlyLabel: 'Monthly',
        yearlyLabel: 'Yearly',
        plans: [
          { name: 'Starter', price: 'Free', period: '', description: 'Get started and explore your first course at no cost.', features: ['1 Course Access', 'Community Forum', 'Email Support'], buttonText: 'Get Started', highlight: false },
          { name: 'Pro', price: '$20', period: '/mo', description: 'For learners ready to commit to consistent growth.', features: ['Unlimited Courses', '1:1 Mentor Sessions', 'Priority Support', 'Certificate of Completion'], buttonText: 'Start Pro Plan', highlight: true },
          { name: 'Enterprise', price: 'Custom', period: '', description: 'For teams and organizations that need more control.', features: ['Everything in Pro', 'Team Dashboards', 'Dedicated Account Manager', 'Custom Integrations'], buttonText: 'Contact Sales', highlight: false },
        ],
        plansYearly: [
          { name: 'Starter', price: 'Free', period: '', description: 'Get started and explore your first course at no cost.', features: ['1 Course Access', 'Community Forum', 'Email Support'], buttonText: 'Get Started', highlight: false },
          { name: 'Pro', price: '$200', period: '/yr', description: 'For learners ready to commit to consistent growth.', features: ['Unlimited Courses', '1:1 Mentor Sessions', 'Priority Support', 'Certificate of Completion'], buttonText: 'Start Pro Plan', highlight: true },
          { name: 'Enterprise', price: 'Custom', period: '', description: 'For teams and organizations that need more control.', features: ['Everything in Pro', 'Team Dashboards', 'Dedicated Account Manager', 'Custom Integrations'], buttonText: 'Contact Sales', highlight: false },
        ],
        primaryColor: '#0d9488',
        accentColor: '#f59e0b',
        backgroundColor: 'transparent',
        // Explicit, not left to PricingTable's own auto-detect: with backgroundColor
        // 'transparent', its isLightColor() check can't read a real color out of the string
        // and falls back to assuming a dark backdrop (white text) — but this section's actual
        // background (pricing.backgroundColor above) is light (#f8fafc), so that fallback
        // rendered the two non-highlighted cards' text invisible (white-on-near-white).
        textColor: '#0f172a',
      },
      parent: 'pricing-inner',
    },

    testimonials: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'testimonials' },
      nodes: ['testimonials-inner'],
      parent: 'ROOT',
    },
    'testimonials-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['testimonials-label', 'testimonials-h', 'testimonials-grid'],
      parent: 'testimonials',
    },
    'testimonials-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'TESTIMONIALS', fontSize: 12, fontWeight: 'bold', color: '#0d9488', textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'testimonials-inner',
    },
    'testimonials-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'What Our Students Say', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-5xl mb-14' },
      parent: 'testimonials-inner',
    },
    'testimonials-grid': {
      type: { resolvedName: 'Columns' },
      isCanvas: true,
      props: { layout: '2', gap: 32 },
      nodes: ['testimonial-1', 'testimonial-2'],
      parent: 'testimonials-inner',
    },
    'testimonial-1': {
      type: { resolvedName: 'UserTestimonial' },
      props: {
        quote: 'Learning here gave me the structure and support I needed. My mentor helped me stay on track and actually finish what I started.',
        author: 'Alex James',
        title: 'Student, Web Development Track',
        image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
        backgroundColor: '#f8fafc',
        textColor: '#0f172a',
        accentColor: '#0d9488',
        borderRadius: 24,
        padding: 40,
        textAlign: 'left',
        borderOpacity: 8,
      },
      parent: 'testimonials-grid',
    },
    'testimonial-2': {
      type: { resolvedName: 'UserTestimonial' },
      props: {
        quote: 'The mentorship program pushed me further than any course alone could. Having someone to check in with made all the difference.',
        author: 'Maria Gonzalez',
        title: 'Student, Business Fundamentals',
        image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=300&auto=format&fit=crop',
        backgroundColor: '#f8fafc',
        textColor: '#0f172a',
        accentColor: '#0d9488',
        borderRadius: 24,
        padding: 40,
        textAlign: 'left',
        borderOpacity: 8,
      },
      parent: 'testimonials-grid',
    },

    contact: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#f8fafc', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'contact' },
      nodes: ['contact-inner'],
      parent: 'ROOT',
    },
    'contact-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-2xl mx-auto text-center' },
      nodes: ['contact-label', 'contact-h', 'contact-p', 'contact-form'],
      parent: 'contact',
    },
    'contact-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'GET IN TOUCH', fontSize: 12, fontWeight: 'bold', color: '#0d9488', textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'contact-inner',
    },
    'contact-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Sign Up For Free Resources', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-4xl mb-4' },
      parent: 'contact-inner',
    },
    'contact-p': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'Get study tips, course updates, and mentorship opportunities straight to your inbox.', textAlign: 'center', fontSize: 15, color: '#64748b', className: 'mb-10' },
      parent: 'contact-inner',
    },
    'contact-form': {
      type: { resolvedName: 'Form' },
      props: {
        fields: [
          { id: '1', type: 'text', label: 'Your Name', placeholder: 'Enter your name', required: true, mapping: 'first_name' },
          { id: '2', type: 'email', label: 'Your Email', placeholder: 'Enter your email', required: true, mapping: 'email' },
          { id: '3', type: 'textarea', label: 'Message', placeholder: 'Write your message...', required: false },
        ],
        buttonText: 'Send Message',
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 32,
        gap: 16,
        labelColor: '#374151',
        inputBg: '#f8fafc',
        inputBorderColor: '#e2e8f0',
        inputTextColor: '#0f172a',
        buttonBg: '#0d9488',
        buttonTextColor: '#ffffff',
        onSuccess: 'message',
        successMessage: 'Thanks! We will be in touch soon.',
      },
      parent: 'contact-inner',
    },

    blog: {
      type: { resolvedName: 'Section' },
      isCanvas: true,
      props: { backgroundColor: '#ffffff', paddingTop: 100, paddingBottom: 100, paddingTop_mobile: 60, paddingBottom_mobile: 60, id: 'blog' },
      nodes: ['blog-inner'],
      parent: 'ROOT',
    },
    'blog-inner': {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: { className: 'max-w-6xl mx-auto' },
      nodes: ['blog-label', 'blog-h', 'blog-feed'],
      parent: 'blog',
    },
    'blog-label': {
      type: { resolvedName: 'Paragraph' },
      props: { text: 'NEWS & BLOG', fontSize: 12, fontWeight: 'bold', color: '#0d9488', textAlign: 'center', className: 'tracking-widest uppercase mb-3' },
      parent: 'blog-inner',
    },
    'blog-h': {
      type: { resolvedName: 'Heading' },
      props: { text: 'Our Latest News & Blog', level: 'h2', textAlign: 'center', fontWeight: 'black', color: '#0f172a', className: 'text-3xl md:text-5xl mb-14' },
      parent: 'blog-inner',
    },
    'blog-feed': {
      type: { resolvedName: 'BlogFeed' },
      props: {
        columns: 3,
        postCount: 3,
        backgroundColor: 'transparent',
        textColor: '#0f172a',
        queryLogic: 'recent',
        category: 'all',
        showFeaturedImage: true,
        showAuthor: true,
        showReadTime: true,
        paginationType: 'none',
      },
      parent: 'blog-inner',
    },

    footer: {
      type: { resolvedName: 'Footer' },
      props: {
        logo: '/web-templates/mentor/mentor-icon.svg',
        brandName: 'Mentor',
        description: 'Helping learners build real skills through expert-led courses and personalized mentorship.',
        columns: [
          { title: 'Quick Links', links: [{ label: 'About Us', href: '#about' }, { label: 'Pricing', href: '#pricing' }, { label: 'Testimonials', href: '#testimonials' }, { label: 'Blog', href: '#blog' }] },
          { title: 'Resources', links: [{ label: 'Contact Us', href: '#contact' }, { label: 'Support', href: '#contact' }, { label: 'FAQs', href: '#contact' }] },
        ],
        backgroundColor: '#0f172a',
        textColor: '#ffffff',
        accentColor: '#2dd4bf',
        padding: 80,
        fullWidth: false,
        columnsCount: 2,
        showSocial: true,
        socialLinks: [
          { platform: 'twitter', url: '#' },
          { platform: 'linkedin', url: '#' },
          { platform: 'facebook', url: '#' },
          { platform: 'instagram', url: '#' },
        ],
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        titleFontSize: 12,
        linkFontSize: 14,
        titleFontWeight: '900',
        showNewsletter: true,
        newsletterTitle: 'Stay Updated',
        newsletterDescription: 'Get new courses, mentorship openings, and learning tips in your inbox.',
      },
      parent: 'ROOT',
    },
  }),
};
