-- PHASE 48: BLOG SEO & METADATA COLUMNS
ALTER TABLE public.blog_posts 
ADD COLUMN IF NOT EXISTS seo_title TEXT,
ADD COLUMN IF NOT EXISTS canonical_url TEXT,
ADD COLUMN IF NOT EXISTS target_keyword TEXT;
